//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostRegisterMobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostRegisterMobile.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott kategória már létezett!.
        /// </summary>
        public static string TextCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("TextCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban el kívánja végezni a kijelölt módosításokat az adatbázisban?.
        /// </summary>
        public static string TextConfirmChangeSettings {
            get {
                return ResourceManager.GetString("TextConfirmChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban törölni kívánja az adatokat?.
        /// </summary>
        public static string TextConfirmDeleteData {
            get {
                return ResourceManager.GetString("TextConfirmDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni kívánja a form tartalmát?.
        /// </summary>
        public static string TextConfirmFormDelete {
            get {
                return ResourceManager.GetString("TextConfirmFormDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váratlan hiba történt a művelet elvégzése során!.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az adatok mentése sikeresen megtörtént!.
        /// </summary>
        public static string TextSaveSuccess {
            get {
                return ResourceManager.GetString("TextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem került sor módosításokra, mert nem adott meg olyan adatot az űrlapon, ami az eddigi beállításoktól eltérő!.
        /// </summary>
        public static string TextSettingsAlreadyMatch {
            get {
                return ResourceManager.GetString("TextSettingsAlreadyMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott üzlet már létezett!.
        /// </summary>
        public static string TextShopAlreadyExists {
            get {
                return ResourceManager.GetString("TextShopAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenet.
        /// </summary>
        public static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres művelet.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
