//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostRegisterMobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostRegisterMobile.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megjegyzés.
        /// </summary>
        public static string AdditionalInformations {
            get {
                return ResourceManager.GetString("AdditionalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új kategória hozzáadása.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új kiadás rögzítése.
        /// </summary>
        public static string AddNewCost {
            get {
                return ResourceManager.GetString("AddNewCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új bevétel rögzítése.
        /// </summary>
        public static string AddNewIncome {
            get {
                return ResourceManager.GetString("AddNewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új üzlet hozzáadása.
        /// </summary>
        public static string AddNewShop {
            get {
                return ResourceManager.GetString("AddNewShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összeg (Ft).
        /// </summary>
        public static string AmountOfMoney {
            get {
                return ResourceManager.GetString("AmountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Űrlap törlése.
        /// </summary>
        public static string ButtonDeleteForm {
            get {
                return ResourceManager.GetString("ButtonDeleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiválasztott törlése.
        /// </summary>
        public static string ButtonDeleteSelectedItem {
            get {
                return ResourceManager.GetString("ButtonDeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategória.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruházat.
        /// </summary>
        public static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb / Nem üzlet.
        /// </summary>
        public static string CostNotInShop {
            get {
                return ResourceManager.GetString("CostNotInShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadások statisztikái.
        /// </summary>
        public static string CostsStatistics {
            get {
                return ResourceManager.GetString("CostsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ft.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadás dátuma.
        /// </summary>
        public static string DateOfCost {
            get {
                return ResourceManager.GetString("DateOfCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevétel érkezésének dátuma.
        /// </summary>
        public static string DateOfIncome {
            get {
                return ResourceManager.GetString("DateOfIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategória törlése.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Háztartás és élelmiszer.
        /// </summary>
        public static string FoodAndOtherHousehold {
            get {
                return ResourceManager.GetString("FoodAndOtherHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Tervezettel).
        /// </summary>
        public static string ForStringHasPlans {
            get {
                return ResourceManager.GetString("ForStringHasPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Nincs tervezett).
        /// </summary>
        public static string ForStringNoPlans {
            get {
                return ResourceManager.GetString("ForStringNoPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Tervezettel nem számol).
        /// </summary>
        public static string ForStringNotInvolvePlans {
            get {
                return ResourceManager.GetString("ForStringNotInvolvePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuális egyenleg:.
        /// </summary>
        public static string ForStringTextCurrentBalance {
            get {
                return ResourceManager.GetString("ForStringTextCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egészsségügyi.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbi.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Háztartási gépek és karbantartás .
        /// </summary>
        public static string HouseholdAppliancesAndMaintenance {
            get {
                return ResourceManager.GetString("HouseholdAppliancesAndMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevételi statisztikák.
        /// </summary>
        public static string IncomeStatistics {
            get {
                return ResourceManager.GetString("IncomeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyéb.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezsi.
        /// </summary>
        public static string Overhead {
            get {
                return ResourceManager.GetString("Overhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Költség-előretervezés.
        /// </summary>
        public static string PlanCost {
            get {
                return ResourceManager.GetString("PlanCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előretervezési statisztikák.
        /// </summary>
        public static string PlanCostStatistics {
            get {
                return ResourceManager.GetString("PlanCostStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakbér.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzlet.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldi.
        /// </summary>
        public static string ShopAldi {
            get {
                return ResourceManager.GetString("ShopAldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auchan.
        /// </summary>
        public static string ShopAuch {
            get {
                return ResourceManager.GetString("ShopAuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bershka.
        /// </summary>
        public static string ShopBersh {
            get {
                return ResourceManager.GetString("ShopBersh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C &amp; A.
        /// </summary>
        public static string ShopCA {
            get {
                return ResourceManager.GetString("ShopCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coop.
        /// </summary>
        public static string ShopCoop {
            get {
                return ResourceManager.GetString("ShopCoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM.
        /// </summary>
        public static string ShopDM {
            get {
                return ResourceManager.GetString("ShopDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lidl.
        /// </summary>
        public static string ShopLidl {
            get {
                return ResourceManager.GetString("ShopLidl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Markt.
        /// </summary>
        public static string ShopMM {
            get {
                return ResourceManager.GetString("ShopMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penny Market.
        /// </summary>
        public static string ShopPenny {
            get {
                return ResourceManager.GetString("ShopPenny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rossmann.
        /// </summary>
        public static string ShopRM {
            get {
                return ResourceManager.GetString("ShopRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesco.
        /// </summary>
        public static string ShopTesc {
            get {
                return ResourceManager.GetString("ShopTesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott kategória már létezett!.
        /// </summary>
        public static string TextCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("TextCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban el kívánja végezni a kijelölt módosításokat az adatbázisban?.
        /// </summary>
        public static string TextConfirmChangeSettings {
            get {
                return ResourceManager.GetString("TextConfirmChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban törölni kívánja az adatokat?.
        /// </summary>
        public static string TextConfirmDeleteData {
            get {
                return ResourceManager.GetString("TextConfirmDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztosan törölni kívánja a form tartalmát?.
        /// </summary>
        public static string TextConfirmFormDelete {
            get {
                return ResourceManager.GetString("TextConfirmFormDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váratlan hiba történt a művelet elvégzése során!.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az adatok mentése sikeresen megtörtént!.
        /// </summary>
        public static string TextSaveSuccess {
            get {
                return ResourceManager.GetString("TextSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem került sor módosításokra, mert nem adott meg olyan adatot az űrlapon, ami az eddigi beállításoktól eltérő!.
        /// </summary>
        public static string TextSettingsAlreadyMatch {
            get {
                return ResourceManager.GetString("TextSettingsAlreadyMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott üzlet már létezett!.
        /// </summary>
        public static string TextShopAlreadyExists {
            get {
                return ResourceManager.GetString("TextShopAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiadások kategóriánként.
        /// </summary>
        public static string TitleCostsPerCategory {
            get {
                return ResourceManager.GetString("TitleCostsPerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzenet.
        /// </summary>
        public static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új bevétel címe.
        /// </summary>
        public static string TitleOfIncome {
            get {
                return ResourceManager.GetString("TitleOfIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Előretervezés címe.
        /// </summary>
        public static string TitleOfPlanCost {
            get {
                return ResourceManager.GetString("TitleOfPlanCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres művelet.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
